#!/usr/bin/env bash
# Bash script with minimum commands to automate fix:
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
