#!/usr/bin/env bash
# This script extends previous exercise command and shows line carrrying bash word, thus allowing you to easily get the PID of your Bash process
# You cant use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
